/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Conexoes.ConexaoMySql;
import Controller.ControllerCliente;
import Controller.ControllerPedidoVenda;
import Controller.ControllerPedidoVendasProdutos;
import Controller.ControllerProdutos;
import Controller.ControllerProdutosPedidoVendasProdutos;
import Controller.ControllerVendasCliente;
import Model.ModelCliente;
import Model.ModelPedidoVenda;
import Model.ModelPedidoVendasProdutos;
import Model.ModelProdutos;
import Model.ModelProdutosPedidoVendasProdutos;
import Model.ModelVendasCliente;
import Util.LiveDatas;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Live Digital Center
 */
public class TelaPedidoVendas extends javax.swing.JFrame {

    ControllerCliente controllerCliente = new ControllerCliente();
    ModelCliente modelCliente = new ModelCliente();
    ArrayList<ModelCliente> listaModelClientes = new ArrayList<>();

    ControllerProdutos controllerProduto = new ControllerProdutos();
    ModelProdutos modelProdutos = new ModelProdutos();
    ArrayList<ModelProdutos> listaModelProdutos = new ArrayList<>();

    ArrayList<ModelVendasCliente> listaModelVendasCliente = new ArrayList<>();
    ControllerVendasCliente controllerVendasCliente = new ControllerVendasCliente();

    ControllerPedidoVenda controllerPedidoVendas = new ControllerPedidoVenda();
    ModelPedidoVenda modelPedidoVendas = new ModelPedidoVenda();

    ControllerPedidoVendasProdutos controllerPedidoVendaProduto = new ControllerPedidoVendasProdutos();
    ModelPedidoVendasProdutos modelPedidoVendasProduto = new ModelPedidoVendasProdutos();
    ArrayList<ModelPedidoVendasProdutos> listaModelPedidoVendaProdutos = new ArrayList<>();

    ControllerProdutosPedidoVendasProdutos controllerProdutosPedidoVendasProdutos = new ControllerProdutosPedidoVendasProdutos();
    ModelProdutosPedidoVendasProdutos modelProdutosPedidoVendasProdutos = new ModelProdutosPedidoVendasProdutos();
    ArrayList<ModelProdutosPedidoVendasProdutos> listaModelProdutosPedidoVendasProdutos = new ArrayList<>();

    LiveDatas datas = new LiveDatas();
    String SalvarAlterar;

    /**
     * Creates new form TelaVendas
     */
    public TelaPedidoVendas() {
        initComponents();
        setLocationRelativeTo(null);
        listarClientes();
        listarProdutos();
        limparFormulario();
        carregarVendas();
        preencherCodCliePeloCombo();
        preencherCodProdPeloCombo();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldCodCliente = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldCoProduto = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        uJComboBoxNCliente = new componentes.UJComboBox();
        jLabel21 = new javax.swing.JLabel();
        uJComboBoxProduto = new componentes.UJComboBox();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldNuVenda = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jButtonAdicionar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableVendasProdutos = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldDesconto = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldValorTotal = new javax.swing.JTextField();
        jButtonRemoverPr = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldNPedidoVenda = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableConsuVendaProdutos = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pedido Vendas » Live Vendas Versão 01.019");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel5.setBackground(new java.awt.Color(0, 70, 121));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setBackground(new java.awt.Color(51, 153, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("FACTURA PROFORMA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Cód. Cliente:");

        jTextFieldCodCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCodClienteFocusLost(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Cód. Produto:");

        jTextFieldCoProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCoProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCoProdutoFocusLost(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Nome do Cliente:");

        uJComboBoxNCliente.setAutocompletar(true);
        uJComboBoxNCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uJComboBoxNCliente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                uJComboBoxNClientePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Nome do Produto:");

        uJComboBoxProduto.setAutocompletar(true);
        uJComboBoxProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uJComboBoxProduto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                uJComboBoxProdutoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Nº da Venda:");

        jTextFieldNuVenda.setEditable(false);
        jTextFieldNuVenda.setBackground(new java.awt.Color(153, 255, 204));
        jTextFieldNuVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Quantidade:");

        jTextFieldQuantidade.setBackground(new java.awt.Color(153, 255, 204));
        jTextFieldQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonAdicionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Add_Shopping_Cart_16.png"))); // NOI18N
        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jTableVendasProdutos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableVendasProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Produto", "Nome Produto", "Quantidade", "Valor Unit.", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableVendasProdutos);
        if (jTableVendasProdutos.getColumnModel().getColumnCount() > 0) {
            jTableVendasProdutos.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTableVendasProdutos.getColumnModel().getColumn(1).setPreferredWidth(320);
            jTableVendasProdutos.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTableVendasProdutos.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTableVendasProdutos.getColumnModel().getColumn(4).setPreferredWidth(60);
        }

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Desconto 0%:");

        jTextFieldDesconto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDescontoFocusLost(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Valor Total:");

        jTextFieldValorTotal.setEditable(false);
        jTextFieldValorTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonRemoverPr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRemoverPr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Do_Not_Disturb_16.png"))); // NOI18N
        jButtonRemoverPr.setText("Remover Produto");
        jButtonRemoverPr.setPreferredSize(new java.awt.Dimension(110, 35));
        jButtonRemoverPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverPrActionPerformed(evt);
            }
        });

        jButtonNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Plus_16.png"))); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.setPreferredSize(new java.awt.Dimension(100, 35));
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Save_16.png"))); // NOI18N
        jButtonGuardar.setText("Salvar Proforma");
        jButtonGuardar.setPreferredSize(new java.awt.Dimension(110, 35));
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Cancel_16.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(110, 35));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Nº da Factura:");

        jTextFieldNPedidoVenda.setBackground(new java.awt.Color(153, 255, 204));
        jTextFieldNPedidoVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRemoverPr, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jTextFieldCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jTextFieldCoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(uJComboBoxProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(uJComboBoxNCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23))
                                .addGap(43, 43, 43))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNuVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel27)
                            .addComponent(jButtonAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNPedidoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uJComboBoxNCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldCoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uJComboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel21))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNuVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNPedidoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdicionar))
                        .addGap(3, 3, 3)))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonRemoverPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(8, 8, 8)
                        .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(8, 8, 8)
                        .addComponent(jTextFieldDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Realizar Pedido Venda", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Pesquisa:");

        jTableConsuVendaProdutos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableConsuVendaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código da Venda", "Nome do Cliente", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsuVendaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsuVendaProdutosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableConsuVendaProdutos);

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Refresh_16.png"))); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setPreferredSize(new java.awt.Dimension(100, 35));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/eliminar.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setPreferredSize(new java.awt.Dimension(110, 35));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Search_16.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonImprimir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Print_16.png"))); // NOI18N
        jButtonImprimir.setText("Imprimir Proforma");
        jButtonImprimir.setPreferredSize(new java.awt.Dimension(110, 35));
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPesquisar)))
                        .addGap(0, 140, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consultar/Excluir/Imprimir", jPanel3);

        jPanel6.setBackground(new java.awt.Color(0, 70, 121));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCodClienteFocusLost
        // TODO add your handling code here:
        try {

            modelCliente = controllerCliente.getClienteController(Integer.parseInt(jTextFieldCodCliente.getText()));
            uJComboBoxNCliente.setSelectedItem(modelCliente.getCliNome());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cliente não existe", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldCodClienteFocusLost

    private void jTextFieldCoProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCoProdutoFocusLost
        // TODO add your handling code here:
        try {

            modelProdutos = controllerProduto.retornaProdutoController(Integer.parseInt(jTextFieldCoProduto.getText()));
            uJComboBoxProduto.setSelectedItem(modelProdutos.getProNome());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Produto e código do produto não existe", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldCoProdutoFocusLost

    private void uJComboBoxNClientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_uJComboBoxNClientePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        try {

            if (uJComboBoxNCliente.isPopupVisible()) {
                preencherCodCliePeloCombo();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cliente não existe", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_uJComboBoxNClientePopupMenuWillBecomeInvisible

    private void uJComboBoxProdutoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_uJComboBoxProdutoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        try {
            if (uJComboBoxProduto.isPopupVisible()) {
                preencherCodProdPeloCombo();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Produto e código do produto não existe", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_uJComboBoxProdutoPopupMenuWillBecomeInvisible

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        int linha = jTableConsuVendaProdutos.getSelectedRow();
        int codigoPedidoVenda = (int) jTableConsuVendaProdutos.getValueAt(linha, 0);
        listaModelProdutos = new ArrayList<>();
        listaModelProdutosPedidoVendasProdutos = controllerProdutosPedidoVendasProdutos.getListaProdutosPedidoVendasProdutosController(codigoPedidoVenda);

        if (controllerPedidoVendaProduto.excluirVendasProdutosController(codigoPedidoVenda)) {
            if (controllerPedidoVendas.excluirPedidoVendaController(codigoPedidoVenda)) {
                JOptionPane.showMessageDialog(this, "Pedido de venda excluida com sucesso", "Informação", JOptionPane.INFORMATION_MESSAGE);
                carregarVendas();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir o pedido de venda", "Erro", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir o pedido de venda", "Erro", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        // TODO add your handling code here:
        if (jTextFieldQuantidade.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor preencher os campos vazios", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            modelProdutos = controllerProduto.retornaProdutoController(Integer.parseInt(jTextFieldCoProduto.getText()));

            DefaultTableModel modelo = (DefaultTableModel) jTableVendasProdutos.getModel();
            int cont = 0;
            double quantidade = 0;
            quantidade = Double.parseDouble(jTextFieldQuantidade.getText());
            for (int i = 0; i < cont; i++) {
                modelo.setNumRows(0);
            }
            modelo.addRow(new Object[]{
                modelProdutos.getIdProduto(),
                modelProdutos.getProNome(),
                jTextFieldQuantidade.getText(),
                modelProdutos.getProValor(),
                quantidade * modelProdutos.getProValor()
            });
            somarValorTotalProdutos();
        }
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jTextFieldDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDescontoFocusLost
        // TODO add your handling code here:
        somarValorTotalProdutos();
    }//GEN-LAST:event_jTextFieldDescontoFocusLost

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        jButtonGuardar.setEnabled(true);
        SalvarAlterar = "salvar";
        limparFormulario();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        int codigoPedidoVenda = 0, codigoProduto =0;
        double desconto = 0;
        listaModelPedidoVendaProdutos = new ArrayList<>();

        if (jTextFieldDesconto.getText().equals("")) {
            //modelVendas.setVenDesconto(0);
            desconto = 0;

        } else {
            desconto = Double.parseDouble(jTextFieldDesconto.getText());
        }

        if (!jTextFieldNuVenda.getText().equals("")) {
            modelPedidoVendas.setIdvendas(Integer.parseInt(jTextFieldNuVenda.getText()));
        }
        modelPedidoVendas.setFk_cliente(Integer.parseInt(jTextFieldCodCliente.getText()));
        try {
            modelPedidoVendas.setPvDatavenda(datas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        } catch (Exception e) {
        }

        modelPedidoVendas.setPvValorliquido(Double.parseDouble(jTextFieldValorTotal.getText()));
        modelPedidoVendas.setPvValorbruto(Double.parseDouble(jTextFieldValorTotal.getText()) + desconto);
        modelPedidoVendas.setPvDesconto(desconto);
        modelPedidoVendas.setPvN_pedido_venda(jTextFieldNPedidoVenda.getText());

        if (SalvarAlterar.equals("salvar")) {

            //salvar vendas
            codigoPedidoVenda = controllerPedidoVendas.salvarPedidoVendaController(modelPedidoVendas);
            if (codigoPedidoVenda > 0) {
                JOptionPane.showMessageDialog(this, "Pedido de venda salvo com Sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar o pedido da venda!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            int cont = jTableVendasProdutos.getRowCount();
            for (int i = 0; i < cont; i++) {
                modelPedidoVendasProduto = new ModelPedidoVendasProdutos();
                modelPedidoVendasProduto.setProduto((int) jTableVendasProdutos.getValueAt(i, 0));
                modelPedidoVendasProduto.setVendas(codigoPedidoVenda);
                modelPedidoVendasProduto.setVenProValor((double) jTableVendasProdutos.getValueAt(i, 3));
                modelPedidoVendasProduto.setVenProQuantidade(Integer.parseInt(jTableVendasProdutos.getValueAt(i, 2).toString()));
                listaModelPedidoVendaProdutos.add(modelPedidoVendasProduto);
            }

            //salvar os produtos do pedido da venda
            if (controllerPedidoVendaProduto.salvarVendasProdutosController(listaModelPedidoVendaProdutos)) {
//                JOptionPane.showMessageDialog(this, "Produtos do pedido da venda salvo com Sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                carregarVendas();
                limparFormulario();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar produtos da venda!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            jButtonGuardar.setEnabled(true);
        } else {
            //Inicio Alterar
            //Retornar para o estoque e excluir produtos da venda
            int linha = jTableConsuVendaProdutos.getSelectedRow();
            codigoPedidoVenda = (int) jTableConsuVendaProdutos.getValueAt(linha, 0);
            listaModelProdutos = new ArrayList<>();
            listaModelProdutosPedidoVendasProdutos = controllerProdutosPedidoVendasProdutos.getListaProdutosPedidoVendasProdutosController(codigoPedidoVenda);

            if (controllerPedidoVendaProduto.excluirVendasProdutosController(codigoPedidoVenda)) {
                JOptionPane.showMessageDialog(this, "Pedido de venda excluida com sucesso", "Informação", JOptionPane.INFORMATION_MESSAGE);
                carregarVendas();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir o pedido de venda", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            //Fim Alterar

            if (controllerPedidoVendas.atualizarPedidoVendaController(modelPedidoVendas)) {
                JOptionPane.showMessageDialog(this, "Pedido de venda alterada com Sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar o Pedido da Venda!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            //adicionar produtos na lista para salvar

            int cont = jTableVendasProdutos.getRowCount();
            for (int i = 0; i < cont; i++) {
                codigoProduto = (int) jTableVendasProdutos.getValueAt(i, 0);
                modelPedidoVendasProduto = new ModelPedidoVendasProdutos();
                modelProdutos = new ModelProdutos();
                
                modelPedidoVendasProduto.setProduto(codigoProduto);
                modelPedidoVendasProduto.setVendas(codigoPedidoVenda);
                modelPedidoVendasProduto.setVenProValor((double) jTableVendasProdutos.getValueAt(i, 3));
                modelPedidoVendasProduto.setVenProQuantidade(Integer.parseInt(jTableVendasProdutos.getValueAt(i, 2).toString()));
                listaModelPedidoVendaProdutos.add(modelPedidoVendasProduto);
            }

            //salvar os produtos do pedido da venda
            if (controllerPedidoVendaProduto.salvarVendasProdutosController(listaModelPedidoVendaProdutos)) {
//                JOptionPane.showMessageDialog(this, "Produtos do pedido da venda salvo com Sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                carregarVendas();
                limparFormulario();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar produtos da venda!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            jButtonGuardar.setEnabled(true);
        }

    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        jButtonGuardar.setEnabled(true);
        SalvarAlterar = "alterar";
        int linha = jTableConsuVendaProdutos.getSelectedRow();
        int codigoVenda = (int) jTableConsuVendaProdutos.getValueAt(linha, 0);
        listaModelProdutosPedidoVendasProdutos = controllerProdutosPedidoVendasProdutos.getListaProdutosPedidoVendasProdutosController(codigoVenda);
        DefaultTableModel modelo = (DefaultTableModel) jTableVendasProdutos.getModel();
        modelo.setNumRows(0);

        for (int i = 0; i < listaModelProdutosPedidoVendasProdutos.size(); i++) {
            jTextFieldNuVenda.setText(String.valueOf(listaModelProdutosPedidoVendasProdutos.get(i).getModelPedidoVendasProdutos().getVendas()));
            modelo.addRow(new Object[]{
                listaModelProdutosPedidoVendasProdutos.get(i).getModelProdutos().getIdProduto(),
                listaModelProdutosPedidoVendasProdutos.get(i).getModelProdutos().getProNome(),
                listaModelProdutosPedidoVendasProdutos.get(i).getModelPedidoVendasProdutos().getVenProQuantidade(),
                listaModelProdutosPedidoVendasProdutos.get(i).getModelPedidoVendasProdutos().getVenProValor(),
                listaModelProdutosPedidoVendasProdutos.get(i).getModelPedidoVendasProdutos().getVenProQuantidade()
                * listaModelProdutosPedidoVendasProdutos.get(i).getModelPedidoVendasProdutos().getVenProValor()
            });

        }

        somarValorTotalProdutos();
        jTabbedPane1.setSelectedIndex(0);

    }//GEN-LAST:event_jButtonEditarActionPerformed
    private Connection connection = new ConexaoMySql().conectar();
    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        // TODO add your handling code here:

        //método de imprimir 
        if (!jTextFieldNuVenda.getText().equals("")) {
            Map p = new HashMap();
            p.put("idpedidovendas", jTextFieldNuVenda.getText());
            JasperReport report;
            JasperPrint print;
            try {
                report = JasperCompileManager.compileReport(new File("").getAbsolutePath()
                        + "/src/Relatorios/relPedidoVendas.jrxml");
                print = JasperFillManager.fillReport(report, p, connection);
                JasperViewer view = new JasperViewer(print, false);
                view.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Logos/log.png")));
                view.setTitle("Imprimir Factura Proforma");
                view.setVisible(true);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void jTableConsuVendaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsuVendaProdutosMouseClicked
        // TODO add your handling code here:
        int fila = jTableConsuVendaProdutos.rowAtPoint(evt.getPoint());
        jTextFieldNuVenda.setText(jTableConsuVendaProdutos.getValueAt(fila, 0).toString());
    }//GEN-LAST:event_jTableConsuVendaProdutosMouseClicked

    private void jButtonRemoverPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverPrActionPerformed
        // TODO add your handling code here:
        try {

            int linha = jTableVendasProdutos.getSelectedRow();
            DefaultTableModel modelo = (DefaultTableModel) jTableVendasProdutos.getModel();
            modelo.removeRow(linha);
            somarValorTotalProdutos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Deves seleccionar um produto", "Alerta", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButtonRemoverPrActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        jButtonGuardar.setEnabled(true);
        limparFormulario();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) this.jTableConsuVendaProdutos.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.jTableConsuVendaProdutos.setRowSorter(classificador);
        String texto = jTextFieldPesquisar.getText();

        classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void preencherCodProdPeloCombo() {
        modelProdutos = controllerProduto.retornaProdutoController(uJComboBoxProduto.getSelectedItem().toString());
        jTextFieldCoProduto.setText(String.valueOf(modelProdutos.getIdProduto()));
    }

    private void preencherCodCliePeloCombo() {
        modelCliente = controllerCliente.getClienteController(uJComboBoxNCliente.getSelectedItem().toString());
        jTextFieldCodCliente.setText(String.valueOf(modelCliente.getIdCliente()));
    }

    public void limparFormulario() {
        jTextFieldNuVenda.setText("");
        jTextFieldNPedidoVenda.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldDesconto.setText("");
        jTextFieldValorTotal.setText("");
        DefaultTableModel modelo = (DefaultTableModel) jTableVendasProdutos.getModel();
        modelo.setNumRows(0);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPedidoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPedidoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPedidoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPedidoVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPedidoVendas().setVisible(true);
            }
        });
    }

    private void somarValorTotalProdutos() {
        double soma = 0, valor;
        int cont = jTableVendasProdutos.getRowCount();
        for (int i = 0; i < cont; i++) {
            valor = (double) jTableVendasProdutos.getValueAt(i, 4);
            soma = soma + valor;

        }
        jTextFieldValorTotal.setText(String.valueOf(soma));
        aplicarDesconto();
    }

    private void aplicarDesconto() {

        try {
            jTextFieldValorTotal.setText(String.valueOf(Double.parseDouble(jTextFieldValorTotal.getText()) - Double.parseDouble(jTextFieldDesconto.getText())));
        } catch (NumberFormatException e) {
        }

    }

    private void listarClientes() {

        listaModelClientes = controllerCliente.getListaClienteController();
        uJComboBoxNCliente.removeAllItems();

        for (int i = 0; i < listaModelClientes.size(); i++) {
            uJComboBoxNCliente.addItem(listaModelClientes.get(i).getCliNome());
        }
    }

    private void listarProdutos() {

        listaModelProdutos = controllerProduto.retornarListaProdutoController();
        uJComboBoxProduto.removeAllItems();

        for (int i = 0; i < listaModelProdutos.size(); i++) {
            uJComboBoxProduto.addItem(listaModelProdutos.get(i).getProNome());
        }
    }

    public void carregarVendas() {
        DefaultTableModel modelo = (DefaultTableModel) jTableConsuVendaProdutos.getModel();
        listaModelVendasCliente = controllerVendasCliente.getListaPedidoVendasClienteController();

        int cont = listaModelVendasCliente.size();
        modelo.setNumRows(0);
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelVendasCliente.get(i).getModelPedidoVendas().getIdvendas(),
                listaModelVendasCliente.get(i).getModelClientes().getCliNome(),
                listaModelVendasCliente.get(i).getModelPedidoVendas().getPvDatavenda()
            });

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonCancelar;
    public static javax.swing.JButton jButtonEditar;
    public static javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonRemoverPr;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableConsuVendaProdutos;
    private javax.swing.JTable jTableVendasProdutos;
    private javax.swing.JTextField jTextFieldCoProduto;
    private javax.swing.JTextField jTextFieldCodCliente;
    private javax.swing.JTextField jTextFieldDesconto;
    private javax.swing.JTextField jTextFieldNPedidoVenda;
    private javax.swing.JTextField jTextFieldNuVenda;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldQuantidade;
    private javax.swing.JTextField jTextFieldValorTotal;
    private componentes.UJComboBox uJComboBoxNCliente;
    private componentes.UJComboBox uJComboBoxProduto;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Logos/log.png"))); //To change body of generated methods, choose Tools | Templates.
    }
}
