/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ModelHora;
import Model.ModelSessaoUsuario;
import Model.ModelUsuarios;
import Conexoes.ConexaoMySql;
import java.awt.Component;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.ModelUsuario;

/**
 *
 * @author Aula
 */
public class ViewPrincipal extends javax.swing.JFrame {

    ConexaoMySql conecta = new ConexaoMySql();
    TelaCliente cliente = new TelaCliente();
    TelaProduto produto = new TelaProduto();
    TelaUsuario usuario = new TelaUsuario();
    TelaVendas vendas = new TelaVendas();
    TelaPedidoVendas pedidovendas = new TelaPedidoVendas();
    TelaCadastroDataVenci vencimento = new TelaCadastroDataVenci();
    TelaValidarSistema validarSistema = new TelaValidarSistema();
    TelaPDV pdv = new TelaPDV();
    ModelSessaoUsuario modelSessaoUsuario = new ModelSessaoUsuario();
    ModelUsuarios modelUsuario = new ModelUsuarios();

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
        setIcont();
        setarUsuario();
        vendas.limparFormulario();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Date data = new Date();
        DateFormat formatadorD = DateFormat.getDateInstance(DateFormat.LONG);
        jlData.setText(formatadorD.format(data));

        ModelHora mostrahora = new ModelHora();
        mostrahora.lerhora();
        jLabel5Hora.setText("" + mostrahora.hora);

        timer1.start();

        //metódo de setar a imagem no label referente ao db
        if (conecta != null) {
            jLabelConexao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Toggle_On_32.png")));
        } else {
            jLabelConexao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Toggle_Off_32.png")));
        }
        
        //metódo de setar a data de vencimento do sistema 
        conecta.conectar();
        conecta.executarSQL("select * from tb_vencimento");
        try {
            conecta.getResultSet().last();
            char [] datav = conecta.getResultSet().getString("data_vencimento").toCharArray();
            lbllicenca.setText("O sistema expira dia: "+datav[0]+datav[1]+"/"+datav[2]+datav[3]+"/"+datav[4]+datav[5]+datav[6]+datav[7]);
        } catch (SQLException ex) {
            Logger.getLogger(ViewPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        uJPanelImagem1 = new componentes.UJPanelImagem();
        jPanel1 = new javax.swing.JPanel();
        jbClientes = new javax.swing.JButton();
        jbProdutos = new javax.swing.JButton();
        jbUsuario = new javax.swing.JButton();
        jbVendas = new javax.swing.JButton();
        jbPDV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbProforma = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jlData = new javax.swing.JLabel();
        jLabel5Hora = new javax.swing.JLabel();
        jLabelConexao = new javax.swing.JLabel();
        lbllogin = new javax.swing.JLabel();
        lblacesso = new javax.swing.JLabel();
        lbllicenca = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jmiSair = new javax.swing.JMenuItem();
        jMenuItemLogof = new javax.swing.JMenuItem();
        jMenuCadastros = new javax.swing.JMenu();
        jmiClientes = new javax.swing.JMenuItem();
        jmiProdutos = new javax.swing.JMenuItem();
        jmiUsuarios = new javax.swing.JMenuItem();
        jMenuVendas = new javax.swing.JMenu();
        jMenuItemvendas = new javax.swing.JMenuItem();
        jMenuConfigurações = new javax.swing.JMenu();
        jMenuItemLicenca = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Vendas e Controle de Estoque » Live Vendas Versão 01.019");

        uJPanelImagem1.setImagem(new java.io.File("C:\\Users\\Live Digital\\Documents\\NetBeansProjects\\LiveVendas019.1\\src\\Logos\\telavendas2.png"));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 51))); // NOI18N

        jbClientes.setBackground(new java.awt.Color(51, 51, 51));
        jbClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbClientes.setForeground(new java.awt.Color(255, 255, 255));
        jbClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Team_32.png"))); // NOI18N
        jbClientes.setText("Clientes");
        jbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClientesActionPerformed(evt);
            }
        });

        jbProdutos.setBackground(new java.awt.Color(51, 51, 51));
        jbProdutos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbProdutos.setForeground(new java.awt.Color(255, 255, 255));
        jbProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Product_32.png"))); // NOI18N
        jbProdutos.setText("Produtos");
        jbProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProdutosActionPerformed(evt);
            }
        });

        jbUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jbUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jbUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Male_User_32.png"))); // NOI18N
        jbUsuario.setText("Usuários");
        jbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUsuarioActionPerformed(evt);
            }
        });

        jbVendas.setBackground(new java.awt.Color(51, 51, 51));
        jbVendas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbVendas.setForeground(new java.awt.Color(255, 255, 255));
        jbVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Shopping_Cart_32.png"))); // NOI18N
        jbVendas.setText("Vendas");
        jbVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVendasActionPerformed(evt);
            }
        });

        jbPDV.setBackground(new java.awt.Color(51, 51, 51));
        jbPDV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbPDV.setForeground(new java.awt.Color(255, 255, 255));
        jbPDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Buying_32.png"))); // NOI18N
        jbPDV.setText("PDV");
        jbPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPDVActionPerformed(evt);
            }
        });

        jbProforma.setBackground(new java.awt.Color(51, 51, 51));
        jbProforma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbProforma.setForeground(new java.awt.Color(255, 255, 255));
        jbProforma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Add_File_32.png"))); // NOI18N
        jbProforma.setText("Factura Proforma");
        jbProforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProformaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbProdutos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbVendas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbPDV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbProforma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jbClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPDV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbProforma)
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Workspace_32.png"))); // NOI18N
        jLabel4.setText("Logado como:");

        jlData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlData.setForeground(new java.awt.Color(255, 255, 255));
        jlData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Calendar_32.png"))); // NOI18N
        jlData.setText("data");

        jLabel5Hora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5Hora.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5Hora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Schedule_32.png"))); // NOI18N
        jLabel5Hora.setText("Data/Hora de login:");

        jLabelConexao.setBackground(new java.awt.Color(255, 255, 255));
        jLabelConexao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelConexao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConexao.setText("Conexão");

        lbllogin.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbllogin.setForeground(new java.awt.Color(255, 255, 255));
        lbllogin.setText("Login");

        lblacesso.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblacesso.setForeground(new java.awt.Color(255, 255, 255));
        lblacesso.setText("Acesso");

        lbllicenca.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbllicenca.setForeground(new java.awt.Color(255, 255, 255));
        lbllicenca.setText("Licença");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbllogin, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(lblacesso, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbllicenca, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelConexao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5Hora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jlData, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelConexao)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5Hora)
                .addComponent(jlData)
                .addComponent(lbllogin)
                .addComponent(lblacesso)
                .addComponent(lbllicenca))
        );

        javax.swing.GroupLayout uJPanelImagem1Layout = new javax.swing.GroupLayout(uJPanelImagem1);
        uJPanelImagem1.setLayout(uJPanelImagem1Layout);
        uJPanelImagem1Layout.setHorizontalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        uJPanelImagem1Layout.setVerticalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(298, 30));

        jMenuArquivo.setBackground(new java.awt.Color(255, 255, 255));
        jMenuArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Home_16.png"))); // NOI18N
        jMenuArquivo.setText("Arquivos");
        jMenuArquivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuArquivoActionPerformed(evt);
            }
        });

        jmiSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmiSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Close_Window_16.png"))); // NOI18N
        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jmiSair);

        jMenuItemLogof.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemLogof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Shutdown_16.png"))); // NOI18N
        jMenuItemLogof.setText("Logoff");
        jMenuItemLogof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogofActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemLogof);

        jMenuBar1.add(jMenuArquivo);

        jMenuCadastros.setBackground(new java.awt.Color(255, 255, 255));
        jMenuCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_iMac_16.png"))); // NOI18N
        jMenuCadastros.setText("Cadastros");
        jMenuCadastros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jmiClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jmiClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Team_16.png"))); // NOI18N
        jmiClientes.setText("Clientes");
        jmiClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClientesActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jmiClientes);

        jmiProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jmiProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Product_16.png"))); // NOI18N
        jmiProdutos.setText("Produtos");
        jmiProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProdutosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jmiProdutos);

        jmiUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jmiUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Male_User_16.png"))); // NOI18N
        jmiUsuarios.setText("Usuários");
        jmiUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jmiUsuarios);

        jMenuBar1.add(jMenuCadastros);

        jMenuVendas.setBackground(new java.awt.Color(255, 255, 255));
        jMenuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Add_Shopping_Cart_16.png"))); // NOI18N
        jMenuVendas.setText("Vendas");
        jMenuVendas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVendasActionPerformed(evt);
            }
        });

        jMenuItemvendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemvendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Shopping_Cart_16.png"))); // NOI18N
        jMenuItemvendas.setText("Vendas");
        jMenuItemvendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemvendasActionPerformed(evt);
            }
        });
        jMenuVendas.add(jMenuItemvendas);

        jMenuBar1.add(jMenuVendas);

        jMenuConfigurações.setBackground(new java.awt.Color(255, 255, 255));
        jMenuConfigurações.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Administrative_Tools_16.png"))); // NOI18N
        jMenuConfigurações.setText("Configurações");
        jMenuConfigurações.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuConfigurações.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConfiguraçõesActionPerformed(evt);
            }
        });

        jMenuItemLicenca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemLicenca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Plus_16.png"))); // NOI18N
        jMenuItemLicenca.setText("Cadastro de Licença");
        jMenuItemLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLicencaActionPerformed(evt);
            }
        });
        jMenuConfigurações.add(jMenuItemLicenca);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icons8_Key_2_16.png"))); // NOI18N
        jMenuItem1.setText("Validar Licença do Sistema");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuConfigurações.add(jMenuItem1);

        jMenuBar1.add(jMenuConfigurações);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        // TODO add your handling code here:
        if (confirmacao(this, "Deseja Realmente Sair do Sistema?")) {

        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jmiClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClientesActionPerformed
        // TODO add your handling code here:

//        new TelaCliente().setVisible(true);
        if (cliente == null) {
            cliente = new View.TelaCliente();
            cliente.toFront();
            cliente.setVisible(true);
            cliente.setResizable(false);
        } else {
            cliente.setVisible(true);
            cliente.setResizable(false);
        }

    }//GEN-LAST:event_jmiClientesActionPerformed

    private void jmiProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProdutosActionPerformed
        // TODO add your handling code here:

        if (produto == null) {
            produto = new View.TelaProduto();
            produto.setVisible(true);
            produto.setResizable(false);
        } else {
            produto.setVisible(true);
            produto.setResizable(false);
        }


    }//GEN-LAST:event_jmiProdutosActionPerformed

    private void jmiUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUsuariosActionPerformed
        // TODO add your handling code here:

        if (usuario == null) {
            usuario = new View.TelaUsuario();
            usuario.setVisible(true);
            usuario.setResizable(false);
        } else {
            usuario.setVisible(true);
            usuario.setResizable(false);
        }

    }//GEN-LAST:event_jmiUsuariosActionPerformed

    private void jMenuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuVendasActionPerformed

    private void jMenuItemvendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemvendasActionPerformed
        // TODO add your handling code here:
        if (vendas == null) {
            vendas = new View.TelaVendas();
            vendas.setVisible(true);
            vendas.setResizable(false);
        } else {
            vendas.setVisible(true);
            vendas.setResizable(false);
        }
        vendas.jTabbedPane1.setSelectedIndex(0);

    }//GEN-LAST:event_jMenuItemvendasActionPerformed

    private void jbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClientesActionPerformed
        // TODO add your handling code here:
        if (cliente == null) {
            cliente = new View.TelaCliente();
            cliente.toFront();
            cliente.setVisible(true);
            cliente.setResizable(false);
        } else {
            cliente.setVisible(true);
            cliente.setResizable(false);
        }
    }//GEN-LAST:event_jbClientesActionPerformed

    private void jbProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProdutosActionPerformed
        // TODO add your handling code here:
        if (produto == null) {
            produto = new View.TelaProduto();
            produto.setVisible(true);
            produto.setResizable(false);
        } else {
            produto.setVisible(true);
            produto.setResizable(false);
        }
    }//GEN-LAST:event_jbProdutosActionPerformed

    private void jbVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVendasActionPerformed
//        // TODO add your handling code here:
        if (vendas == null) {
            vendas = new View.TelaVendas();
            vendas.setVisible(true);
            vendas.setResizable(false);
        } else {
            vendas.setVisible(true);
            vendas.setResizable(false);
        }
        vendas.jTabbedPane1.setSelectedIndex(0);

    }//GEN-LAST:event_jbVendasActionPerformed

    private void jbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUsuarioActionPerformed
        // TODO add your handling code here:
        if (usuario == null) {
            usuario = new View.TelaUsuario();
            usuario.setVisible(true);
            usuario.setResizable(false);
        } else {
            usuario.setVisible(true);
            usuario.setResizable(false);
        }
    }//GEN-LAST:event_jbUsuarioActionPerformed

    private void jbPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPDVActionPerformed
        // TODO add your handling code here:
//        new ViewPDV().setVisible(true);

        if (pdv == null) {
            pdv = new TelaPDV();
            pdv.toFront();
            pdv.setVisible(true);
            pdv.setResizable(false);
        } else {
            pdv.setVisible(true);
            pdv.setResizable(false);
        }
    }//GEN-LAST:event_jbPDVActionPerformed

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        // TODO add your handling code here:
        ModelHora mostrahora = new ModelHora();
        mostrahora.lerhora();
        jLabel5Hora.setText("" + mostrahora.hora);
    }//GEN-LAST:event_timer1OnTime

    private void jMenuArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuArquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuArquivoActionPerformed

    private void jMenuItemLogofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogofActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaLogin().setVisible(true);
    }//GEN-LAST:event_jMenuItemLogofActionPerformed

    private void jbProformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProformaActionPerformed
        // TODO add your handling code here:
        if (pedidovendas == null) {
            pedidovendas = new TelaPedidoVendas();
            pedidovendas.toFront();
            pedidovendas.setVisible(true);
            pedidovendas.setResizable(false);
        } else {
            pedidovendas.setVisible(true);
            pedidovendas.setResizable(false);
        }

    }//GEN-LAST:event_jbProformaActionPerformed

    private void jMenuItemLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLicencaActionPerformed
        // TODO add your handling code here:
        vencimento.setVisible(true);
    }//GEN-LAST:event_jMenuItemLicencaActionPerformed

    private void jMenuConfiguraçõesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConfiguraçõesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuConfiguraçõesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        validarSistema.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void setarUsuario() {
        lbllogin.setText(modelSessaoUsuario.login);
        lblacesso.setText(modelSessaoUsuario.acesso);

        if (lblacesso.getText().equals("admin")) {
            jMenuArquivo.setEnabled(true);
            jMenuCadastros.setEnabled(true);
            jMenuVendas.setEnabled(true);
            jMenuConfigurações.setEnabled(!true);
            jbClientes.setEnabled(true);
            jbProdutos.setEnabled(true);
            jbVendas.setEnabled(true);
            jbUsuario.setEnabled(true);
            jbPDV.setEnabled(true);
            vendas.jButtonEditar.setEnabled(true);
            vendas.jButtonExcluir.setEnabled(true);

        } else if (lblacesso.getText().equals("desenvolvedor")) {
            jMenuArquivo.setEnabled(true);
            jMenuCadastros.setEnabled(true);
            jMenuConfigurações.setEnabled(true);
            jMenuVendas.setEnabled(true);
            jbClientes.setEnabled(true);
            jbProdutos.setEnabled(true);
            jbVendas.setEnabled(true);
            jbUsuario.setEnabled(true);
            jbPDV.setEnabled(true);
            vendas.jButtonEditar.setEnabled(true);
            vendas.jButtonExcluir.setEnabled(true);

        } else {
            jMenuArquivo.setEnabled(true);
            jMenuCadastros.setEnabled(!true);
            jMenuVendas.setEnabled(true);
            jMenuConfigurações.setEnabled(!true);
            jbClientes.setEnabled(!true);
            jbProdutos.setEnabled(!true);
            jbVendas.setEnabled(true);
            jbUsuario.setEnabled(!true);
            jbPDV.setEnabled(true);
            vendas.jButtonEditar.setEnabled(!true);
            vendas.jButtonExcluir.setEnabled(!true);
        }
    }

    public static boolean confirmacao(Component frame, String msg) {
        Object[] opcoes = {"Sim", "Não"};
        int opcao = JOptionPane.showOptionDialog(frame, msg, "Confirmar", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);

        if (opcao == JOptionPane.YES_NO_CANCEL_OPTION) {
            return true;

        } else {
            return false;

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5Hora;
    private javax.swing.JLabel jLabelConexao;
    public static javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenu jMenuCadastros;
    public static javax.swing.JMenu jMenuConfigurações;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemLicenca;
    private javax.swing.JMenuItem jMenuItemLogof;
    private javax.swing.JMenuItem jMenuItemvendas;
    public static javax.swing.JMenu jMenuVendas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JButton jbClientes;
    public static javax.swing.JButton jbPDV;
    public static javax.swing.JButton jbProdutos;
    public static javax.swing.JButton jbProforma;
    public static javax.swing.JButton jbUsuario;
    public static javax.swing.JButton jbVendas;
    private javax.swing.JLabel jlData;
    private javax.swing.JMenuItem jmiClientes;
    private javax.swing.JMenuItem jmiProdutos;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiUsuarios;
    public static javax.swing.JLabel lblacesso;
    public static javax.swing.JLabel lbllicenca;
    public static javax.swing.JLabel lbllogin;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    private componentes.UJPanelImagem uJPanelImagem1;
    // End of variables declaration//GEN-END:variables

    private void setIcont() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Logos/shopping-cart.jpg"))); //To change body of generated methods, choose Tools | Templates.
    }
}
